packages_list:
  - libcap1
  - gcc
  - gcc-c++
  - glibc
  - glibc-devel
  - ksh
  - libaio1
  - libaio-devel
  - libelf-devel
  - libstdc++6
  - libstdc++-devel
  - libXi6
  - libXtst6
  - sysstat
  - unixODBC
  - unixODBC-devel
  - xdpyinfo
  - unzip
  - make
rm_packages_list:
  - gettext-runtime-mini
kernel_params:
# Shared memory and semaphore
# look for document 226209.1 in oracle support for details
  kernel.sem: 250 32000 100 128
  kernel.shmmni: 4096
# System memory is 512G, minus Linux reserved is 504G.  Give ourselves
# 16G more free and we're left with 488G.  Divide by page size (4096)
# and we get the shmall value below:
  kernel.shmall: 127926272
# Half of the memory reserved for Oracle above (bytes).
  kernel.shmmax: 261993005056
# For 1Gbps with 1ms latency 16MB buffer
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.ipv4.tcp_rmem: 4096 87380 16777216
  net.ipv4.tcp_wmem: 4096 65536 16777216
# Minimize swap file use
  vm.swappiness: 10
  vm.dirty_background_ratio: 5
  vm.dirty_ratio: 10
# Max open file descriptors 512 * db processes + room for os
  fs.file-max: 409600
# Shorten keep alive of connections
  net.ipv4.tcp_keepalive_time: 300
  net.ipv4.tcp_keepalive_intvl: 60
  net.ipv4.tcp_keepalive_probes: 10
# maximize port range
  net.ipv4.ip_local_port_range: 9000 65500

# Oracle user limits
soft_no_file: 4096
hard_no_file: 65536
soft_nproc: 2047
hard_nproc: 16384
soft_stack: 10240
hard_stack: 32768
# mem lock 90% of RAM
soft_memlock: 1887437
hard_memlock: 1887437